In [2]:
import numpy as np

In [3]:
import numpy as np

a = np.array([a for a in range(10) if a%2 !=0])
print(a)

[1 3 5 7 9]


In [9]:
print(np.ones([3,3],dtype=bool))


print(np.zeros([3,3]))


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [11]:
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [12]:
np.set_printoptions(threshold = 1000)

In [13]:
#reset the set_printoptions
np.set_printoptions(edgeitems=3,
                    infstr='inf',
                    linewidth=75,
                    nanstr='nan',
                    precision=8,
                    suppress=False,
                    threshold=1000,
                    formatter=None)

In [160]:
a = np.arange(10)
a

In [14]:
import numpy as np
data = np.genfromtxt('/content/drive/MyDrive/dataset/Iris.csv',delimiter=',',dtype='object',names=True)

spc = np.array([i[5] for i in data])

In [15]:
data.dtype
data_arr = data.reshape(150,-1)

In [16]:
data_arr[:10]

array([[(b'1', b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa')],
       [(b'2', b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa')],
       [(b'3', b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa')],
       [(b'4', b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa')],
       [(b'5', b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa')],
       [(b'6', b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa')],
       [(b'7', b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa')],
       [(b'8', b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa')],
       [(b'9', b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa')],
       [(b'10', b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa')]],
      dtype=[('Id', 'O'), ('SepalLengthCm', 'O'), ('SepalWidthCm', 'O'), ('PetalLengthCm', 'O'), ('PetalWidthCm', 'O'), ('Species', 'O')])

In [17]:
data.dtype.names

('Id',
 'SepalLengthCm',
 'SepalWidthCm',
 'PetalLengthCm',
 'PetalWidthCm',
 'Species')

In [18]:
data['SepalLengthCm']

array([b'5.1', b'4.9', b'4.7', b'4.6', b'5.0', b'5.4', b'4.6', b'5.0',
       b'4.4', b'4.9', b'5.4', b'4.8', b'4.8', b'4.3', b'5.8', b'5.7',
       b'5.4', b'5.1', b'5.7', b'5.1', b'5.4', b'5.1', b'4.6', b'5.1',
       b'4.8', b'5.0', b'5.0', b'5.2', b'5.2', b'4.7', b'4.8', b'5.4',
       b'5.2', b'5.5', b'4.9', b'5.0', b'5.5', b'4.9', b'4.4', b'5.1',
       b'5.0', b'4.5', b'4.4', b'5.0', b'5.1', b'4.8', b'5.1', b'4.6',
       b'5.3', b'5.0', b'7.0', b'6.4', b'6.9', b'5.5', b'6.5', b'5.7',
       b'6.3', b'4.9', b'6.6', b'5.2', b'5.0', b'5.9', b'6.0', b'6.1',
       b'5.6', b'6.7', b'5.6', b'5.8', b'6.2', b'5.6', b'5.9', b'6.1',
       b'6.3', b'6.1', b'6.4', b'6.6', b'6.8', b'6.7', b'6.0', b'5.7',
       b'5.5', b'5.5', b'5.8', b'6.0', b'5.4', b'6.0', b'6.7', b'6.3',
       b'5.6', b'5.5', b'5.5', b'6.1', b'5.8', b'5.0', b'5.6', b'5.7',
       b'5.7', b'6.2', b'5.1', b'5.7', b'6.3', b'5.8', b'7.1', b'6.3',
       b'6.5', b'7.6', b'4.9', b'7.3', b'6.7', b'7.2', b'6.5', b'6.4',
      

In [37]:
url = '/content/drive/MyDrive/dataset/Iris.csv'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength

array([ nan,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [20]:
# print(np.set_printoptions())
mn = min(sepallength)
mx = max(sepallength)
c = mx - mn
ls = []
def norm(sepallength):
  for i in sepallength:
    a = (i - mn)/ c
    ls.append(a)

  return np.array(ls)


np.set_printoptions(precision=3)
print(norm(sepallength))


[0.222 0.167 0.111 0.083 0.194 0.306 0.083 0.194 0.028 0.167 0.306 0.139
 0.139 0.    0.417 0.389 0.306 0.222 0.389 0.222 0.306 0.222 0.083 0.222
 0.139 0.194 0.194 0.25  0.25  0.111 0.139 0.306 0.25  0.333 0.167 0.194
 0.333 0.167 0.028 0.222 0.194 0.056 0.028 0.194 0.222 0.139 0.222 0.083
 0.278 0.194 0.75  0.583 0.722 0.333 0.611 0.389 0.556 0.167 0.639 0.25
 0.194 0.444 0.472 0.5   0.361 0.667 0.361 0.417 0.528 0.361 0.444 0.5
 0.556 0.5   0.583 0.639 0.694 0.667 0.472 0.389 0.333 0.333 0.417 0.472
 0.306 0.472 0.667 0.556 0.361 0.333 0.333 0.5   0.417 0.194 0.361 0.389
 0.389 0.528 0.222 0.389 0.556 0.417 0.778 0.556 0.611 0.917 0.167 0.833
 0.667 0.806 0.611 0.583 0.694 0.389 0.417 0.583 0.611 0.944 0.944 0.472
 0.722 0.361 0.944 0.556 0.667 0.806 0.528 0.5   0.583 0.806 0.861 1.
 0.583 0.556 0.5   0.944 0.556 0.583 0.472 0.722 0.667 0.722 0.417 0.694
 0.667 0.667 0.556 0.611 0.528 0.444]


In [21]:
sum(np.exp(np.array([1,2,3])))
np.exp(np.array([1,2,3]))

array([ 2.718,  7.389, 20.086])

In [22]:
np.exp(-9)

0.00012340980408667956

In [23]:
data.dtype.names

('Id',
 'SepalLengthCm',
 'SepalWidthCm',
 'PetalLengthCm',
 'PetalWidthCm',
 'Species')

In [38]:
url = '/content/drive/MyDrive/dataset/Iris.csv'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength

array([ nan,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [41]:
np.percentile(sepallength,100)


# data

7.9

In [42]:
sepallength.max()

7.9

In [39]:
url = '/content/drive/MyDrive/dataset/Iris.csv'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')


# np.random.  iris_2d
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4,size=20)] = np.nan
print(iris_2d)

[[b'Id' b'SepalLengthCm' b'SepalWidthCm' b'PetalLengthCm' b'PetalWidthCm'
  b'Species']
 [b'1' b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'2' b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'3' b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4' b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5' b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'6' b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'7' b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'8' nan b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'9' b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'10' b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'11' b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'12' b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'13' b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [nan b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'15' b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'16' b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'17' b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'18' b'5.1' b'3.5' b'1.4' b'0.3' b'Iris

In [25]:
np.where(np.isnan(iris_2d[:,:4].astype('float')))

(array([  8,  14,  24,  24,  34,  53,  58,  60,  66,  67,  79,  87,  94,
         98, 103, 107, 137, 138, 143, 144]),
 array([1, 0, 2, 3, 0, 1, 1, 3, 3, 2, 0, 0, 1, 1, 3, 3, 1, 3, 3, 3]))

In [26]:
iris_2d[:,:5]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', nan, b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [nan, b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4', b'0.3

In [40]:
url = '/content/drive/MyDrive/dataset/Iris.csv'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [41]:
dt = iris_2d[np.where((iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0))]
dt

array([[1. , 5.1, 3.5, 1.4],
       [2. , 4.9, 3. , 1.4],
       [3. , 4.7, 3.2, 1.3],
       [4. , 4.6, 3.1, 1.5]])

In [42]:
import numpy as np


data = np.array([[1,2,3],
                 [4,10,6],
                 [7,8,9]
                 ])
print(data)




clm1 = data[:,0]
clm2 = data[:,1]

print(clm1)
print(clm2)


correlation = np.corrcoef(clm1, clm2)[0,1]
print(f"Correlation between column 1 and column 2: {correlation}")

[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
[1 4 7]
[ 2 10  8]
Correlation between column 1 and column 2: 0.720576692122892


In [30]:
np.isnan(iris_2d).any()

False

In [43]:
# Input
url = '/content/drive/MyDrive/dataset/Iris.csv'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [44]:
iris_2d

array([[  nan,   nan,   nan,   nan],
       [  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   nan,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       [  4. ,   4.6,   3.1,   1.5],
       [  5. ,   5. ,   3.6,   1.4],
       [  6. ,   5.4,   3.9,   1.7],
       [  7. ,   4.6,   3.4,   1.4],
       [  8. ,   5. ,   3.4,   1.5],
       [  9. ,   4.4,   2.9,   1.4],
       [ 10. ,   4.9,   3.1,   1.5],
       [ 11. ,   5.4,   3.7,   1.5],
       [ 12. ,   4.8,   3.4,   1.6],
       [ 13. ,   4.8,   3. ,   nan],
       [ 14. ,   nan,   3. ,   1.1],
       [ 15. ,   5.8,   4. ,   1.2],
       [ 16. ,   5.7,   4.4,   1.5],
       [ 17. ,   5.4,   3.9,   nan],
       [ 18. ,   5.1,   nan,   1.4],
       [ 19. ,   5.7,   3.8,   1.7],
       [ 20. ,   5.1,   3.8,   1.5],
       [ 21. ,   5.4,   3.4,   1.7],
       [ 22. ,   5.1,   3.7,   1.5],
       [ 23. ,   4.6,   3.6,   1. ],
       [ 24. ,   5.1,   3.3,   1.7],
       [ 25. ,   4.8,   3.4,   1.9],
       [ 26. ,   5. ,   3. ,   1.6],
 

In [34]:
iris_2d[np.isnan(iris_2d)] = 0

In [35]:
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 0. , 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0. ],
       [5.8, 0. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0. ],
       [5.7, 3.8, 0. , 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 0. , 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0. ],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [45]:
# Input
url = '/content/drive/MyDrive/dataset/Iris.csv'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [46]:
iris

array([[b'Id', b'SepalLengthCm', b'SepalWidthCm', b'PetalLengthCm',
        b'PetalWidthCm', b'Species'],
       [b'1', b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'2', b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'3', b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4', b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5', b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'6', b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'7', b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'8', b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'9', b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'10', b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'11', b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'12', b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'13', b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'14', b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       

In [48]:
np.unique(iris[:,5])

array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica', b'Species'],
      dtype=object)

In [52]:
# Input
url = '/content/drive/MyDrive/dataset/Iris.csv'
iris = np.genfromtxt(url, delimiter=',', dtype='object',skip_header=True)
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [53]:
iris

array([[b'1', b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'2', b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'3', b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4', b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5', b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'6', b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'7', b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'8', b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'9', b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'10', b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'11', b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'12', b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'13', b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'14', b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'15', b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'16', b'5.7', b'4.4', b'1.5', b'0.4', b'

In [54]:
category = np.array(['small', 'medium', 'large'])
condition = [iris[:,2].astype('float') < 3
              ,(3 <= iris[:,2].astype('float')) &  (iris[:,2].astype('float') < 5)
              , 5 <= iris[:,2].astype('float')
            ]

catagoricaldata = np.select(condition, category)
# print(catagoricaldata)
np.column_stack((iris,np.array(catagoricaldata)))


array([[b'1', b'5.1', b'3.5', ..., b'0.2', b'Iris-setosa', 'medium'],
       [b'2', b'4.9', b'3.0', ..., b'0.2', b'Iris-setosa', 'medium'],
       [b'3', b'4.7', b'3.2', ..., b'0.2', b'Iris-setosa', 'medium'],
       ...,
       [b'148', b'6.5', b'3.0', ..., b'2.0', b'Iris-virginica', 'medium'],
       [b'149', b'6.2', b'3.4', ..., b'2.3', b'Iris-virginica', 'medium'],
       [b'150', b'5.9', b'3.0', ..., b'1.8', b'Iris-virginica', 'medium']],
      dtype=object)

In [55]:
np.column_stack((iris,np.array(catagoricaldata)))

array([[b'1', b'5.1', b'3.5', ..., b'0.2', b'Iris-setosa', 'medium'],
       [b'2', b'4.9', b'3.0', ..., b'0.2', b'Iris-setosa', 'medium'],
       [b'3', b'4.7', b'3.2', ..., b'0.2', b'Iris-setosa', 'medium'],
       ...,
       [b'148', b'6.5', b'3.0', ..., b'2.0', b'Iris-virginica', 'medium'],
       [b'149', b'6.2', b'3.4', ..., b'2.3', b'Iris-virginica', 'medium'],
       [b'150', b'5.9', b'3.0', ..., b'1.8', b'Iris-virginica', 'medium']],
      dtype=object)

In [57]:
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]
volume

np.hstack([iris,catagoricaldata[:,np.newaxis]])

array([[b'1', b'5.1', b'3.5', ..., b'0.2', b'Iris-setosa', 'medium'],
       [b'2', b'4.9', b'3.0', ..., b'0.2', b'Iris-setosa', 'medium'],
       [b'3', b'4.7', b'3.2', ..., b'0.2', b'Iris-setosa', 'medium'],
       ...,
       [b'148', b'6.5', b'3.0', ..., b'2.0', b'Iris-virginica', 'medium'],
       [b'149', b'6.2', b'3.4', ..., b'2.3', b'Iris-virginica', 'medium'],
       [b'150', b'5.9', b'3.0', ..., b'1.8', b'Iris-virginica', 'medium']],
      dtype=object)

In [58]:
np.array(catagoricaldata)

array(['medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'small', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'small',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'small', 'small',
       'small', 'medium', 'small', 'small', 'small', 'small', 'medium',
       'small', 'small', 'small', 'medium', 'medium', 'small', 'small',
       'small', 'medium', 'small', 'small', 'small', 'small', 'medium',
       'small', 'medium', 'small', 'small', 'small', 'small', 'small',
       'small', 'medium', 'medium', 'medium', 'small', 'medium', 'small',
       'small', 'medium', 'sma

In [59]:
iris

array([[b'1', b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'2', b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'3', b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4', b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5', b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'6', b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'7', b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'8', b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'9', b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'10', b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'11', b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'12', b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'13', b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'14', b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'15', b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'16', b'5.7', b'4.4', b'1.5', b'0.4', b'

In [60]:
# Import iris keeping the text column intact
url = '/content/drive/MyDrive/dataset/Iris.csv'
iris = np.genfromtxt(url, delimiter=',', dtype='object')



rnd = iris[:,4]


In [61]:
np.random.seed(1000000)
a = np.array(['Iris-setos', 'Iris-versicolor', 'Iris-virginica'])
np.unique(np.random.choice(a, 150, p =[0.5, 0.25, 0.25]),return_counts= True)

(array(['Iris-setos', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'),
 array([83, 29, 38]))